### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by dleadbetter** [performant-software/react-components#173]
Setup a framework for documenting components using the [docs](https://storybook.js.org/addons/@storybook/addon-docs) add-on for Storybook. For a first pass, provide documentation for the following components:

- [x] ListTable
- [x] EmbeddedList
- [x] List
- [x] DataList
- [x] DataTable
- [x] FileUpload
- [x] FileUploadModal
- [x] Items
- [x] ItemCollection
- [x] ItemList
- [x] EditPage
- [x] EditModal
- [ ] DataView

**Comment by dleadbetter** [comment]
@NickLaiacona - Here's a first pass at a very simple component, but just a general idea of what I'm thinking:

```mdx
[//]: # (ArrowButtons.stories.mdx)

<Meta
  title="Components/Semantic UI/ArrowButtons"
  component={ArrowButtons}
/>

<DocHeader
  item={ArrowButtons}
/>

<Canvas>
  <Story name='Default'>
    <ArrowButtons
      onLeft={action('onLeft')}
      onRight={action('onRight')}
    />
  </Story>
</Canvas>

<PropsTable
  item={ArrowButtons}
/>

## More information
Here I can put some more information about whatever else I think is important for developers to know

### Even more stuff
...

### Additional Stories
With more information provided for each story

<Preview>
  <Story name='Another Story'>
    <ArrowButtons
      onLeft={action('onLeft')}
      onRight={action('onRight')}
    />
  </Story>
</Preview>
```

![Screen Shot 2022-10-10 at 4 26 42 PM](https://user-images.githubusercontent.com/20641961/194947054-1cc8f14a-bb47-4b5b-a942-da5a6b4f6735.png)

All of the props and description documentation will be parsed out of the component itself. Additional documentation for specific stories, or just more information that doesn't quite belong in the component can be added using markdown syntax. Thoughts?

**Comment by NickLaiacona** [comment]
This is good. For function type props, it would be desirable to see the parameters and return value types for them.  Here's the syntax used by ProseMirror's [docs](https://prosemirror.net/docs/ref/) to describe function type props:

```
fn(  node: Node, pos: number, parent: Node, index:number ) -> boolean | undefined
```

I like that it has a space for default values and that you can designate which props are optional vs. required.
